### PR TITLE
chore: update flate2 version

### PR DESCRIPTION
**Pull request by yihong0618**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## What's changed and what's your intention?

This patch follow this article to chore flate which maybe faster and can drop cmake
article: https://trifectatech.org/blog/zlib-rs-is-faster-than-c/

also format some Cargo.toml releated the change file 

## PR Checklist
Please convert it to a draft if some of the following conditions are not met.

- [ ] I have written the necessary rustdoc comments.
- [ ] I have added the necessary unit tests and integration tests.
- [ ] This PR requires documentation updates.
- [ ] API changes are backward compatible.
- [ ] Schema or data changes are backward compatible.

### CODE REVIEW

**Review by sunng87 — APPROVED** [review]
Awesome. That's perfect!

**Review by waynexia — APPROVED** [review]
LGTM 🚀

**Comment by yihong0618** [comment]
ci failed seems upstream problem will try to fix it later

**Comment by yihong0618** [comment]
> ci failed seems upstream problem will try to fix it later

no need

**Comment by evenyag** [comment]
https://github.com/GreptimeTeam/greptimedb/actions/runs/13848925444/job/38752767800

Unable to run `nextest` in the release job. Looks like there are some linking issues. Maybe related to this PR.
```
cargo --list | grep nextest || cargo install cargo-nextest --locked

error: linking with `cc` failed: exit status: 1

 = note: some arguments are omitted. use `--verbose` to show all linker arguments
  = note: rust-lld: error: duplicate symbol: crc32
          >>> defined at crc32.c:1016 (src/zlib/crc32.c:1016)
          >>>            0dc752f03a07a721-crc32.o:(crc32) in archive /greptimedb/target/debug/deps/liblibz_sys-3df317acd34adec9.rlib
          >>> defined at lib.rs:99 (src/lib.rs:99)
          >>>            libz_rs_sys-4a09f9934c9134bc.libz_rs_sys.9761070cd71d0df0-cgu.0.rcgu.o:(.text.crc32+0x0) in archive /greptimedb/target/debug/deps/liblibz_rs_sys-4a09f9934c9134bc.rlib
```

**Comment by yihong0618** [comment]
> https://github.com/GreptimeTeam/greptimedb/actions/runs/13848925444/job/38752767800
> 
> Unable to run `nextest` in the release job. Looks like there are some linking issues. Maybe related to this PR.
> 
> ```
> cargo --list | grep nextest || cargo install cargo-nextest --locked
> 
> error: linking with `cc` failed: exit status: 1
> 
> = note: rust-lld: error: duplicate symbol: crc32
>           >>> defined at crc32.c:1016 (src/zlib/crc32.c:1016)
>           >>>            0dc752f03a07a721-crc32.o:(crc32) in archive /greptimedb/target/debug/deps/liblibz_sys-3df317acd34adec9.rlib
>           >>> defined at lib.rs:99 (src/lib.rs:99)
>           >>>            libz_rs_sys-4a09f9934c9134bc.libz_rs_sys.9761070cd71d0df0-cgu.0.rcgu.o:(.text.crc32+0x0) in archive /greptimedb/target/debug/deps/liblibz_rs_sys-4a09f9934c9134bc.rlib
>           
>           rust-lld: error: duplicate symbol: uncompress
>           >>> defined at uncompr.c:83 (src/zlib/uncompr.c:83)
>           >>>            0dc752f03a07a721-uncompr.o:(uncompress) in archive /greptimedb/target/debug/deps/liblibz_sys-3df317acd34adec9.rlib
>           >>> defined at lib.rs:269 (src/lib.rs:269)
>           >>>            libz_rs_sys-4a09f9934c9134bc.libz_rs_sys.9761070cd71d0df0-cgu.0.rcgu.o:(.text.uncompress+0x0) in archive /greptimedb/target/debug/deps/liblibz_rs_sys-4a09f9934c9134bc.rlib
>           
>           rust-lld: error: duplicate symbol: inflate
>           >>> defined at inflate.c:590 (src/zlib/inflate.c:590)
>           >>>            0dc752f03a07a721-inflate.o:(inflate) in archive /greptimedb/target/debug/deps/liblibz_sys-3df317acd34adec9.rlib
>           >>> defined at lib.rs:324 (src/lib.rs:324)
>           >>>            libz_rs_sys-4a09f9934c9134bc.libz_rs_sys.9761070cd71d0df0-cgu.0.rcgu.o:(.text.inflate+0x0) in archive /greptimedb/target/debug/deps/liblibz_rs_sys-4a09f9934c9134bc.rlib
>           
>           rust-lld: error: duplicate symbol: inflateEnd
>           >>> defined at inflate.c:1266 (src/zlib/inflate.c:1266)
>           >>>            0dc752f03a07a721-inflate.o:(inflateEnd) in archive /greptimedb/target/debug/deps/liblibz_sys-3df317acd34adec9.rlib
>           >>> defined at lib.rs:348 (src/lib.rs:348)
>           >>>            libz_rs_sys-4a09f9934c9134bc.libz_rs_sys.9761070cd71d0df0-cgu.0.rcgu.o:(.text.inflateEnd+0x0) in archive /greptimedb/target/debug/deps/liblibz_rs_sys-4a09f9934c9134bc.rlib
> ```

yes the reason is we had other flate2 dependence that use flate2 too
and they seems early version that must on `"libz-sys"`
that is causing the `duplicate symbol` problem.
 
for now in cargo.lock is like below I will try to figure out if can pass the problem,
otherwise maybe better to revert This commit until they fix it. cc @sunng87 
```
[[package]]
name = "flate2"
version = "1.1.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "11faaf5a5236997af9848be0bef4db95824b1d534ebc64d0f0c6cf3e67bd38dc"
dependencies = [
 "crc32fast",
 "libz-rs-sys",
 "libz-sys",
 "miniz_oxide",
]
```
