### PR TITLE
fix: android build

### PR DESCRIPTION
**Pull request by yihong0618**
I hereby agree to the terms of the [GreptimeDB CLA](https://github.com/GreptimeTeam/.github/blob/main/CLA.md).

## Refer to a related PR or issue link (optional)

@WenyXu @sunng87 
This patch finish https://github.com/GreptimeTeam/greptimedb/issues/5322

android build still failed after https://github.com/GreptimeTeam/greptimedb/pull/5327 
need very tiny fix, this patch did it.

error:
make build-android-bin
```cli
   Compiling meta-srv v0.12.0 (/greptimedb/src/meta-srv)
   Compiling datanode v0.12.0 (/greptimedb/src/datanode)
   Compiling cli v0.12.0 (/greptimedb/src/cli)
   Compiling frontend v0.12.0 (/greptimedb/src/frontend)
   Compiling flow v0.12.0 (/greptimedb/src/flow)
   Compiling plugins v0.12.0 (/greptimedb/src/plugins)
   Compiling cmd v0.12.0 (/greptimedb/src/cmd)
error[E0599]: no method named `detect_server_addr` found for struct `meta_srv::metasrv::MetasrvOptions` in the current scope
   --> src/cmd/src/metasrv.rs:276:14
    |
276 |         opts.detect_server_addr();
    |              ^^^^^^^^^^^^^^^^^^ method not found in `MetasrvOptions`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `cmd` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
note: If the build failed due to a missing target, you can run this command:
note: 
note:     rustup target install aarch64-linux-android
make: *** [Makefile:75: build] Error 101
make: *** [build-android-bin] Error 2
```

## PR Checklist
Please convert it to a draft if some of the following conditions are not met.

- [ ] I have written the necessary rustdoc comments.
- [ ] I have added the necessary unit tests and integration tests.
- [ ] This PR requires documentation updates.
- [ ] API changes are backward compatible.
- [ ] Schema or data changes are backward compatible.

### CODE REVIEW

**Comment by yihong0618** [comment]
> https://github.com/GreptimeTeam/greptimedb/blob/0685ba265cf16bf1eb72917bb06daefa8a5a76e9/src/meta-srv/src/metasrv.rs#L207-L235
> 
> Hi @yihong0618,　Thank you for your testing! This typo was introduced by me. I believe it would be better to rename `detect_hostname` to `detect_server_addr` in MetasrvOptions.
> 
> Let me know what you think! 😊

of course will test and change it, thanks for the info, and good night

**Comment by yihong0618** [comment]
> https://github.com/GreptimeTeam/greptimedb/blob/0685ba265cf16bf1eb72917bb06daefa8a5a76e9/src/meta-srv/src/metasrv.rs#L207-L235
> 
> Hi @yihong0618,　Thank you for your testing! This typo was introduced by me. I believe it would be better to rename `detect_hostname` to `detect_server_addr` in MetasrvOptions.
> 
> Let me know what you think! 😊

Done and waiting for the build for testing

**Review by WenyXu — APPROVED** [review]
Thanks!
